services:
  postgres:
    image: postgres:16-alpine
    container_name: lms_postgres
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms
      POSTGRES_PASSWORD: secret
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms -d lms"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: lms_redis
    ports:
      - "63790:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
